import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "outline-variant": "#3c494e",
        "inverse-surface": "#e2e2e2",
        surface: "#121414",
        "secondary-fixed": "#f9d8ff",
        "primary-container": "#00d2ff",
        "surface-bright": "#37393a",
        "on-tertiary": "#313030",
        background: "#121414",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#edb1ff",
        "surface-container-high": "#282a2b",
        "surface-container-lowest": "#0c0f0f",
        outline: "#859399",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#00566a",
        "on-secondary-fixed": "#320046",
        primary: "#a5e7ff",
        "tertiary-fixed-dim": "#c8c6c5",
        "tertiary-container": "#c3c0c0",
        "on-tertiary-fixed": "#1c1b1b",
        "inverse-on-surface": "#2f3131",
        "on-surface-variant": "#bbc9cf",
        "surface-dim": "#121414",
        "inverse-primary": "#00677f",
        "on-tertiary-fixed-variant": "#474746",
        "surface-container-low": "#1a1c1c",
        "primary-fixed-dim": "#47d6ff",
        "on-secondary": "#520070",
        "on-primary-fixed": "#001f28",
        "tertiary-fixed": "#e5e2e1",
        "surface-variant": "#333535",
        "on-primary": "#003543",
        "surface-container": "#1e2020",
        "on-secondary-container": "#e498ff",
        "on-secondary-fixed-variant": "#6e208c",
        "surface-container-highest": "#333535",
        "on-primary-fixed-variant": "#004e60",
        "on-background": "#e2e2e2",
        "secondary-container": "#6e208c",
        tertiary: "#dfdcdb",
        "surface-tint": "#47d6ff",
        "on-surface": "#e2e2e2",
        "on-tertiary-container": "#4f4e4e",
        error: "#ffb4ab",
        secondary: "#edb1ff",
        "primary-fixed": "#b6ebff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        card: "1.5rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "margin-desktop": "64px",
        "container-max": "1280px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "title-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      animation: {
        "nebula-slow": "nebula 15s ease-in-out infinite",
        "nebula-slower": "nebula 20s ease-in-out infinite reverse",
        "spin-slow": "spin 8s linear infinite",
      },
      keyframes: {
        nebula: {
          "0%, 100%": { opacity: "0.4", transform: "scale(1) translate(0,0)" },
          "50%": { opacity: "0.7", transform: "scale(1.05) translate(20px,-20px)" },
        },
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};

export default config;
